### ISSUE TITLE
Plugin never connects on non-flatpak installation

### ISSUE THREAD

**Issue by 3urobeat** [StreamController/OBSPlugin#10]
When StreamController was installed natively, the `__install__.py` script never runs (or fails?), causing the `backend/.venv` directory to be missing. This in turn causes the call to `backend/.venv/bin/activate` to fail when `backend.py` is attempted to be launched.

Related issue: https://github.com/StreamController/StreamController/issues/214

Edit: Looks like a weird dependency issue. Upon cloning the plugin, StreamController tries to execute `__install__.py` which fails at loading `streamcontroller_plugin_tools`. Since this dep is installed, is this a threading issue? I'm not sure. The package was installed in a virtual env, not systemwide (because Arch externally managed reasons)

Edit 2: Yep, this is a virtual environment issue. When installing `streamcontroller_plugin_tools` systemwide, this issue does not appear anymore and the plugin is correctly set up. It also now connects to OBS (whoop whoop) (but throws other errors lol)

Edit 3: Found the issue, the subprocess spawned to run `__install__.py` at `StoreBackend.py:766` uses the system wide python binary. No wonder the venv deps are missing lol

Edit 4: Fixed in PR https://github.com/StreamController/StreamController/pull/221

**Comment by 3urobeat** [comment]
Okay, this is probably caused by StreamController itself and not by the plugin as I thought at first.  
Installing and removing plugins is completely broken for me right now for some reason (it worked previously), I have to take a deeper look.

**Comment by 3urobeat** [comment]
The OBS plugin now works for me! Hurray!

**Comment by Core447** [comment]
Fixed with https://github.com/StreamController/StreamController/pull/221 - thank you!
