### ISSUE TITLE
Add Switch Preview Scene

### ISSUE THREAD

**Issue by kaanelloed** [StreamController/OBSPlugin#11]
First of all, thank you for this great application!

It would be nice to be able to change the preview scene. Just like Switch to Scene, but instead of the scene going live, it goes in the preview.

It can be a new action or an option in the Switch to Scene action.

**Comment by Core447** [comment]
@G4PLS is currently working on a new OBS plugin with many more features and actions. As a result, the current plugin will only receive bug fixes atm.

**Comment by kaanelloed** [comment]
Okay, I'll follow the new plugin. Thank you!

**Comment by Core447** [comment]
> Thank you!

No problem, I hope it's not too urgent...

**Comment by G4PLS** [comment]
It will take a while until the new Plugin goes live
Currently i dont have a lot of time so development is on hold

**Comment by Rinma** [comment]
If someone else finds this issue and wants this feature, just modify the `OBSController.py` in the plugins install folder with this code

```
    def switch_to_scene(self, scene:str) -> None:
        studioModeStatus = self.get_studio_mode_enabled()
        if studioModeStatus.datain["studioModeEnabled"]:
            try:
                self.call(requests.SetCurrentPreviewScene(sceneName=scene))
            except (obswebsocket.exceptions.MessageTimeout,  websocket._exceptions.WebSocketConnectionClosedException, KeyError) as e:
                log.error(e)
        else:
            try:
                self.call(requests.SetCurrentProgramScene(sceneName=scene))
            except (obswebsocket.exceptions.MessageTimeout,  websocket._exceptions.WebSocketConnectionClosedException, KeyError) as e:
                log.error(e)
```

It is not configurable and will always only switch out the preview scene when studio mode is active, but for me, this is all I need for the moment.

Be aware, this change will probably be reverted if the plugin gets an update.
